direction: right
pkg: "package on foss-2025a"
foss: "foss-2025a"
gompi: "gompi-2025a"
gfbf: "gfbf-2025a"
gcc: "GCC"
gcccore: "GCCcore"
pkg -> foss
foss -> gompi
foss -> gfbf
gompi -> gcc
gfbf -> gcc
gcc -> gcccore
