"""Sphinx configuration.

Three builders are configured on purpose, and the build script runs all
three, so the claim that one org source yields per-chapter HTML, a single
consolidated page and an EPUB is tested from the first commit rather than
assumed. That claim is the reason this book is built with Sphinx at all.
"""

import os
import sys

sys.path.insert(0, os.path.abspath("_ext"))

# -- Project information -----------------------------------------------------

project = "What EasyBuild Is Doing"
author = "Rohit Goswami"
copyright = "2026, Rohit Goswami"
release = "0.1.0"
# EPUB3 requires a non-empty version; Sphinx does not derive it from release.
version = "0.1"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx_copybutton",
    "sphinx_design",
    "eb_widget",
    "eb_transcript",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The .rst under source/ is generated by export.el from orgmode/; only
# conf.py, _ext, _static and _templates are authored here.
master_doc = "index"

# No default lexer. The eb directive sets "python" on its own blocks, which
# is where easyconfigs live, and everything else on these pages is prose
# quotes, shell transcripts or eb output. A python default makes Sphinx try
# to lex an ox-rst block quote as code and fail on its own backticks, which
# under -W is a build failure caused entirely by a wrong default.
highlight_language = "none"

nitpicky = True

# -- HTML --------------------------------------------------------------------

html_theme = "shibuya"
html_static_path = ["_static"]
html_title = project
html_copy_source = False
html_show_sourcelink = False

html_theme_options = {
    "github_url": "https://github.com/HaoZeke/what-easybuild-is-doing",
    "nav_links": [
        {"title": "eb-stack", "url": "https://eb-stack.rgoswami.me"},
        {"title": "EasyBuild docs", "url": "https://docs.easybuild.io"},
    ],
}

# Copybutton should not pick up prompts that are not there; easyconfig
# samples are files, not shell sessions.
copybutton_prompt_text = r"\$ "
copybutton_prompt_is_regexp = True

# -- EPUB --------------------------------------------------------------------
# The widgets are absent here by design (see _ext/eb_widget.py). A chapter
# that stops making sense in this build is a chapter that leans on the
# reader running something, which the retention numbers say most will not.

epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright
epub_identifier = "https://github.com/HaoZeke/what-easybuild-is-doing"
epub_scheme = "URL"
epub_show_urls = "footnote"
epub_use_index = False
# The widget assets cannot be used in an EPUB: the visitor emits no mount
# point there and _register_assets links nothing. Sphinx still *copies*
# html_static_path into the output, so without this the book ships a
# stylesheet, a mount script and an encoding table that nothing reads. The
# charmap also has no mimetype Sphinx recognises, which under -W turns that
# dead weight into a failed build.
epub_exclude_files = [
    "search.html",
    "_static/eb-widget.css",
    "_static/eb-widget.js",
    "_static/eb-widget-engine.js",
    "_static/eb-charmap.json",
    "_static/eb-templates.json",
    "_static/eb-hierarchy.json",
]
# eb-transcript.css is deliberately absent from that list. A transcript is
# static text and renders in the EPUB, so its stylesheet belongs there.
