"""Sphinx configuration.

Three builders are configured on purpose, and the build script runs all
three, so the claim that one org source yields per-chapter HTML, a single
consolidated page and an EPUB is tested from the first commit rather than
assumed. That claim is the reason this book is built with Sphinx at all.
"""

import os
import sys

sys.path.insert(0, os.path.abspath("_ext"))

# -- Project information -----------------------------------------------------

project = "EasyBuild: the file, the tree, and the run"
author = "Rohit Goswami"
copyright = "2026, Rohit Goswami"
release = "0.1.0"
# EPUB3 requires a non-empty version; Sphinx does not derive it from release.
version = "0.1"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx_copybutton",
    "sphinx_design",
    "sphinxcontrib.bibtex",
    "eb_widget",
    "eb_transcript",
    "eb_lesson",
    # Dive-in details, and retrieval over the book. Both are html-only by
    # construction; see their modules for what the epub gets instead.
    "eb_knowl",
    "eb_ask",
]

# Bibliography is refs.bib. McCalpin 1995 is the one entry with no DOI.
bibtex_bibfiles = ["refs.bib"]
bibtex_reference_style = "author_year"

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The .rst under source/ is generated by export.el from orgmode/; only
# conf.py, _ext, _static and _templates are authored here.
master_doc = "index"

# No default lexer. The eb directive sets "python" on its own blocks, which
# is where easyconfigs live, and everything else on these pages is prose
# quotes, shell transcripts or eb output. A python default makes Sphinx try
# to lex an ox-rst block quote as code and fail on its own backticks, which
# under -W is a build failure caused entirely by a wrong default.
highlight_language = "none"

nitpicky = True

# -- HTML --------------------------------------------------------------------

html_theme = "shibuya"
html_static_path = ["_static"]
html_extra_path = ["CNAME", "_headers"]
html_baseurl = "https://hpceb.rgoswami.me/"
# Typography and layout for long-form reading, layered over the theme rather
# than replacing it. Scoped to article.yue so navigation keeps the theme's
# own design; see the file for what it changes and why.
html_css_files = ["eb-book.css", "eb-annotate.css"]
# Annotations are the reader's own, stored in their browser and exported by
# them; see _static/eb-annotate.js for the anchoring model and the
# accessibility requirements it has to meet.
html_js_files = [
    "https://cdn.tailwindcss.com",
    ("eb-annotate.js", {"defer": "defer"}),
    ("vangrail-kernel.js", {"defer": "defer"}),
    ("eb-a11y.js", {"defer": "defer"}),
    "hypothesis-config.js",
    ("https://hypothes.is/embed.js", {"async": "async"}),
]
html_title = project
html_use_index = False
html_copy_source = False
html_show_sourcelink = False

html_theme_options = {
    "github_url": "https://github.com/HaoZeke/what-easybuild-is-doing",
    "nav_links": [
        {"title": "Journeys", "url": "journeys"},
        {"title": "RecipeReader", "url": "part-a-recipe"},
        {"title": "StackWalker", "url": "part-a-stack"},
        {"title": "ReframeReader", "url": "part-a-test"},
    ],
}

# Copybutton should not pick up prompts that are not there; easyconfig
# samples are files, not shell sessions.
copybutton_prompt_text = r"\$ "
copybutton_prompt_is_regexp = True

# -- EPUB --------------------------------------------------------------------
# The widgets are absent here by design (see _ext/eb_widget.py). A chapter
# that stops making sense in this build is a chapter that leans on the
# reader running something, which the retention numbers say most will not.

epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright
epub_identifier = "https://github.com/HaoZeke/what-easybuild-is-doing"
epub_scheme = "URL"
epub_show_urls = "footnote"
epub_use_index = False
# The widget assets cannot be used in an EPUB: the visitor emits no mount
# point there and _register_assets links nothing. Sphinx still *copies*
# html_static_path into the output, so without this the book ships a
# stylesheet, a mount script and an encoding table that nothing reads. The
# charmap also has no mimetype Sphinx recognises, which under -W turns that
# dead weight into a failed build.
epub_exclude_files = [
    "search.html",
    # A knowl fetches a fragment and Ask ranks a pack, and an e-reader can do
    # neither. The extensions emit no mount points there, so these assets
    # would be dead weight that the epub builder also has no mimetype for.
    "_static/eb-knowl.css",
    "_static/eb-knowl.js",
    "_static/eb-knowls.json",
    "_static/eb-ask.css",
    "_static/eb-ask.js",
    "_static/eb-ask-pack.json",
    "_static/eb-ask-external.json",
    "_static/vangrail-kernel.js",
    "_static/vangrail_kernel.wasm",
    # Annotations need a browser to store them in.
    "_static/eb-annotate.css",
    "_static/eb-annotate.js",
    "_static/eb-a11y.js",
    "_static/eb-widget.css",
    "_static/eb-widget.js",
    "_static/eb-widget-engine.js",
    "_static/eb-charmap.json",
    "_static/eb-templates.json",
    "_static/eb-hierarchy.json",
    "_static/eb-universe.json",
    # Sphinx leaves this behind when a build is interrupted, and the epub
    # builder then refuses a file it has no mimetype for. Under -W that turns
    # a stale artifact from a previous run into a failed build.
    ".buildinfo.bak",
    "CNAME",
]
# eb-transcript.css is deliberately absent from that list. A transcript is
# static text and renders in the EPUB, so its stylesheet belongs there.


def _uncloak_mailto(app, doctree, fromdocname):
    """Spack specs use name@version. Docutils cloaks those as mailto."""
    from docutils import nodes

    for node in list(doctree.findall(nodes.reference)):
        uri = node.get("refuri", "")
        if not uri.startswith("mailto:"):
            continue
        text = node.astext()
        node.replace_self(nodes.literal(text, text))


def setup(app):
    app.connect("doctree-resolved", _uncloak_mailto)
